version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: anemonas
    restart: always
    environment:
      POSTGRES_DB: anemonas
      POSTGRES_USER: user
      POSTGRES_PASSWORD: coisarada
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

# matem dados mesmo de o container for destruido
volumes:
  postgres-data:
